/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppCrawlerIndexRouteImport } from './routes/app/crawler/index'
import { Route as AppChapterIndexRouteImport } from './routes/app/chapter/index'
import { Route as AppBookIndexRouteImport } from './routes/app/book/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrawlerIndexRoute = AppCrawlerIndexRouteImport.update({
  id: '/crawler/',
  path: '/crawler/',
  getParentRoute: () => AppRoute,
} as any)
const AppChapterIndexRoute = AppChapterIndexRouteImport.update({
  id: '/chapter/',
  path: '/chapter/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIndexRoute = AppBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/book/': typeof AppBookIndexRoute
  '/app/chapter/': typeof AppChapterIndexRoute
  '/app/crawler/': typeof AppCrawlerIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/book': typeof AppBookIndexRoute
  '/app/chapter': typeof AppChapterIndexRoute
  '/app/crawler': typeof AppCrawlerIndexRoute
  '/app/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/book/': typeof AppBookIndexRoute
  '/app/chapter/': typeof AppChapterIndexRoute
  '/app/crawler/': typeof AppCrawlerIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/book/'
    | '/app/chapter/'
    | '/app/crawler/'
    | '/app/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/book'
    | '/app/chapter'
    | '/app/crawler'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/book/'
    | '/app/chapter/'
    | '/app/crawler/'
    | '/app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crawler/': {
      id: '/app/crawler/'
      path: '/crawler'
      fullPath: '/app/crawler/'
      preLoaderRoute: typeof AppCrawlerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chapter/': {
      id: '/app/chapter/'
      path: '/chapter'
      fullPath: '/app/chapter/'
      preLoaderRoute: typeof AppChapterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book/': {
      id: '/app/book/'
      path: '/book'
      fullPath: '/app/book/'
      preLoaderRoute: typeof AppBookIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppBookIndexRoute: typeof AppBookIndexRoute
  AppChapterIndexRoute: typeof AppChapterIndexRoute
  AppCrawlerIndexRoute: typeof AppCrawlerIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppBookIndexRoute: AppBookIndexRoute,
  AppChapterIndexRoute: AppChapterIndexRoute,
  AppCrawlerIndexRoute: AppCrawlerIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
