/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCrawlerRouteImport } from './routes/app/crawler'
import { Route as AppChaptersRouteImport } from './routes/app/chapters'
import { Route as AppBooksRouteImport } from './routes/app/books'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrawlerRoute = AppCrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => AppRoute,
} as any)
const AppChaptersRoute = AppChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/chapters': typeof AppChaptersRoute
  '/app/crawler': typeof AppCrawlerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/chapters': typeof AppChaptersRoute
  '/app/crawler': typeof AppCrawlerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/chapters': typeof AppChaptersRoute
  '/app/crawler': typeof AppCrawlerRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/books'
    | '/app/chapters'
    | '/app/crawler'
    | '/app/dashboard'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/books'
    | '/app/chapters'
    | '/app/crawler'
    | '/app/dashboard'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/books'
    | '/app/chapters'
    | '/app/crawler'
    | '/app/dashboard'
    | '/app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crawler': {
      id: '/app/crawler'
      path: '/crawler'
      fullPath: '/app/crawler'
      preLoaderRoute: typeof AppCrawlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chapters': {
      id: '/app/chapters'
      path: '/chapters'
      fullPath: '/app/chapters'
      preLoaderRoute: typeof AppChaptersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/books': {
      id: '/app/books'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBooksRoute: typeof AppBooksRoute
  AppChaptersRoute: typeof AppChaptersRoute
  AppCrawlerRoute: typeof AppCrawlerRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBooksRoute: AppBooksRoute,
  AppChaptersRoute: AppChaptersRoute,
  AppCrawlerRoute: AppCrawlerRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
