/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppstoreOutlined: typeof import('@ant-design/icons-vue')['AppstoreOutlined']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CalendarOutlined: typeof import('@ant-design/icons-vue')['CalendarOutlined']
    CommentOutlined: typeof import('@ant-design/icons-vue')['CommentOutlined']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    DownSquareOutlined: typeof import('@ant-design/icons-vue')['DownSquareOutlined']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HistoryOutlined: typeof import('@ant-design/icons-vue')['HistoryOutlined']
    Login: typeof import('./components/Login.vue')['default']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    RadiusBottomleftOutlined: typeof import('@ant-design/icons-vue')['RadiusBottomleftOutlined']
    ReadOutlined: typeof import('@ant-design/icons-vue')['ReadOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
